# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Compile HTML 
      run: |
        cd src
        npm install @shd101wyy/mume
        node compile.js
        cd ..
        ./src/link.sh .
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "Adding files to stash"
        git add */*.html
        git add QIC890/lecture01.html
        git stash
        git stash show
        echo "Checking out master"
        git fetch
        git checkout -f master
        git stash show
        git stash pop
        git status
        git add */*.html
        git commit -m "Compiled changes from develop"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
